name: go-cache

on: workflow_dispatch

jobs:
  ci:
    name: Running CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Cache Go modules
        uses: actions/cache@v4.0.2
        id: go-modules
        with:
          path: |
           ~/.cache/go-build
           ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.3

      - name: Build
        run: go build -o myapp .

      - name: Test
        run: go test ./...
